name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make npm -y
          sudo npm install --global
      - name: Build binary
        run: make install-npm
      - name: Publish binary
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN  }}' > ${{ github.workspace }}/.npmrc
          npm publish
